## Default config file used by Github Pages, copy the config from one of the other config files to use:
## _config-0g
## _config-1g
## _config-3g

repo: minvws/nl-covid19-notification-app-website

version: 0g

collections:
  questions:
    output: true
    permalink: /:categories/:name/
  questions-in-app:
    output: true
    permalink: /:categories/:name/
  questions-scanner:
    output: true
    permalink: /:categories/:name/
  questions-scanner-in-app:
    output: true
    permalink: /:categories/:name/
  announcements:
    output: false  

defaults:
  -
    scope:
      path: "_questions/nl"
      type: "questions"
    values:
      layout: content
      categories:
      - nl
      - faq
      lang: nl
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
  -
    scope:
      path: "_questions/en"
      type: "questions"
    values:
      layout: content
      categories:
      - en
      - faq
      lang: en
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
  -
    scope:
      path: "_questions-in-app/en"
      type: "questions-in-app"
    values:
      layout: in-app-question
      categories:
      - en
      - faq-in-app
      lang: en
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
      webonly: false
  -
    scope:
      path: "_questions-in-app/nl"
      type: "questions-in-app"
    values:
      layout: in-app-question
      categories:
      - nl
      - faq-in-app
      lang: nl
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
      webonly: false
  -
    scope:
      path: "_questions-scanner/nl"
      type: "questions-scanner"
    values:
      layout: content
      categories:
      - nl
      - faq-scanner
      lang: nl
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
  -
    scope:
      path: "_questions-scanner/en"
      type: "questions-scanner"
    values:
      layout: content
      categories:
      - en
      - faq-scanner
      lang: en
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
  -
    scope:
      path: "_questions-scanner-in-app/en"
      type: "questions-scanner-in-app"
    values:
      layout: in-app-question
      categories:
      - en
      - faq-scanner-in-app
      lang: en
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
      webonly: false
  -
    scope:
      path: "_questions-scanner-in-app/nl"
      type: "questions-scanner-in-app"
    values:
      layout: in-app-question
      categories:
      - nl
      - faq-scanner-in-app
      lang: nl
      showBreadCrumbs: true
      showContact: true
      showOnFAQoverview: true
      webonly: false

sass:
  style: compressed
  load_paths:
    - css

include:
  - .well-known

exclude:
  - vendor
  - print-portal
  - dashboard-spa
  - Gemfile
  - Gemfile.lock
  - CODE_OF_CONDUCT.md
  - README.md
  - README.announcements.md
  - README.content-translations.md
  - README.development.md
  - README.i18n.md
  - README.requirements.md
  - LICENSES.md
  - LICENSE.txt
  - LICENSE.pdf
  - example-content-page.md
  - .sass-cache
  - .history
  - auth.php
  - auth2.php
  - generate-statistics-graphic.html

plugins:
  - "jekyll-github-metadata"
  - "jekyll-sitemap"
  - "jekyll-redirect-from"
  # - "jekyll-seo-tag"

incremental: false

